// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.29.0
// 	protoc        v3.21.12
// source: protos/cql_beam.proto

package cql_beam_go_proto

import (
	cql_result_go_proto "github.com/google/cql/protos/cql_result_go_proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The results of the evaluated CQL for a particular id and timestamp.
type BeamResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The id of the result. Usually this is the Patient ID but can be overriden.
	Id *string `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	// The timestamp at which the CQL was evaluated.
	EvaluationTimestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=evaluation_timestamp,json=evaluationTimestamp,proto3,oneof" json:"evaluation_timestamp,omitempty"`
	// The result of the CQL evaluation.
	Result *cql_result_go_proto.Libraries `protobuf:"bytes,3,opt,name=result,proto3,oneof" json:"result,omitempty"`
}

func (x *BeamResult) Reset() {
	*x = BeamResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_cql_beam_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BeamResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeamResult) ProtoMessage() {}

func (x *BeamResult) ProtoReflect() protoreflect.Message {
	mi := &file_protos_cql_beam_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeamResult.ProtoReflect.Descriptor instead.
func (*BeamResult) Descriptor() ([]byte, []int) {
	return file_protos_cql_beam_proto_rawDescGZIP(), []int{0}
}

func (x *BeamResult) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *BeamResult) GetEvaluationTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.EvaluationTimestamp
	}
	return nil
}

func (x *BeamResult) GetResult() *cql_result_go_proto.Libraries {
	if x != nil {
		return x.Result
	}
	return nil
}

// Indicates an error that occured at some phase of CQL processing.
type BeamError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// A message describing the error.
	ErrorMessage *string `protobuf:"bytes,1,opt,name=error_message,json=errorMessage,proto3,oneof" json:"error_message,omitempty"`
	// A URI referencing the error's source. This could be a file path to a
	// malformed input, resource ID, or other item.
	SourceUri *string `protobuf:"bytes,2,opt,name=source_uri,json=sourceUri,proto3,oneof" json:"source_uri,omitempty"`
}

func (x *BeamError) Reset() {
	*x = BeamError{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_cql_beam_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BeamError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeamError) ProtoMessage() {}

func (x *BeamError) ProtoReflect() protoreflect.Message {
	mi := &file_protos_cql_beam_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeamError.ProtoReflect.Descriptor instead.
func (*BeamError) Descriptor() ([]byte, []int) {
	return file_protos_cql_beam_proto_rawDescGZIP(), []int{1}
}

func (x *BeamError) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

func (x *BeamError) GetSourceUri() string {
	if x != nil && x.SourceUri != nil {
		return *x.SourceUri
	}
	return ""
}

var File_protos_cql_beam_proto protoreflect.FileDescriptor

var file_protos_cql_beam_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x63, 0x71, 0x6c, 0x5f, 0x62, 0x65, 0x61,
	0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x63, 0x71, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x73, 0x2f, 0x63, 0x71, 0x6c, 0x5f, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xda, 0x01, 0x0a, 0x0a, 0x42, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x12, 0x13, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00,
	0x52, 0x02, 0x69, 0x64, 0x88, 0x01, 0x01, 0x12, 0x52, 0x0a, 0x14, 0x65, 0x76, 0x61, 0x6c, 0x75,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x48, 0x01, 0x52, 0x13, 0x65, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x88, 0x01, 0x01, 0x12, 0x38, 0x0a, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x63, 0x71, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4c,
	0x69, 0x62, 0x72, 0x61, 0x72, 0x69, 0x65, 0x73, 0x48, 0x02, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x88, 0x01, 0x01, 0x42, 0x05, 0x0a, 0x03, 0x5f, 0x69, 0x64, 0x42, 0x17, 0x0a, 0x15,
	0x5f, 0x65, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x22, 0x7a, 0x0a, 0x09, 0x42, 0x65, 0x61, 0x6d, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x28, 0x0a,
	0x0d, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x88, 0x01, 0x01, 0x12, 0x22, 0x0a, 0x0a, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x5f, 0x75, 0x72, 0x69, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x09, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x55, 0x72, 0x69, 0x88, 0x01, 0x01, 0x42, 0x10, 0x0a, 0x0e, 0x5f,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x0d, 0x0a,
	0x0b, 0x5f, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x75, 0x72, 0x69, 0x42, 0x32, 0x50, 0x01,
	0x5a, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x63, 0x71, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x63,
	0x71, 0x6c, 0x5f, 0x62, 0x65, 0x61, 0x6d, 0x5f, 0x67, 0x6f, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_cql_beam_proto_rawDescOnce sync.Once
	file_protos_cql_beam_proto_rawDescData = file_protos_cql_beam_proto_rawDesc
)

func file_protos_cql_beam_proto_rawDescGZIP() []byte {
	file_protos_cql_beam_proto_rawDescOnce.Do(func() {
		file_protos_cql_beam_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_cql_beam_proto_rawDescData)
	})
	return file_protos_cql_beam_proto_rawDescData
}

var file_protos_cql_beam_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protos_cql_beam_proto_goTypes = []interface{}{
	(*BeamResult)(nil),                    // 0: google.cql.proto.BeamResult
	(*BeamError)(nil),                     // 1: google.cql.proto.BeamError
	(*timestamppb.Timestamp)(nil),         // 2: google.protobuf.Timestamp
	(*cql_result_go_proto.Libraries)(nil), // 3: google.cql.proto.Libraries
}
var file_protos_cql_beam_proto_depIdxs = []int32{
	2, // 0: google.cql.proto.BeamResult.evaluation_timestamp:type_name -> google.protobuf.Timestamp
	3, // 1: google.cql.proto.BeamResult.result:type_name -> google.cql.proto.Libraries
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_protos_cql_beam_proto_init() }
func file_protos_cql_beam_proto_init() {
	if File_protos_cql_beam_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_cql_beam_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BeamResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_cql_beam_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BeamError); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_protos_cql_beam_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_protos_cql_beam_proto_msgTypes[1].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_cql_beam_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_cql_beam_proto_goTypes,
		DependencyIndexes: file_protos_cql_beam_proto_depIdxs,
		MessageInfos:      file_protos_cql_beam_proto_msgTypes,
	}.Build()
	File_protos_cql_beam_proto = out.File
	file_protos_cql_beam_proto_rawDesc = nil
	file_protos_cql_beam_proto_goTypes = nil
	file_protos_cql_beam_proto_depIdxs = nil
}
